<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="0" failures="2" skipped="2" tests="10" time="0.173" timestamp="2021-01-13T16:30:26.615853" hostname="infinity-Inspiron-N4010"><testcase classname="tst_001.test_001" name="test_001" time="0.002" /><testcase classname="tst_001.test_001" name="test_002" time="0.001" /><testcase classname="tst_001.test_002" name="test_comparacion" time="0.001" /><testcase classname="tst_002.test_002" name="test_002" time="0.001" /><testcase classname="tst_002.test_002" name="test_003" time="0.001" /><testcase classname="tst_002.test_002" name="test_004" time="0.001"><skipped type="pytest.skip" message="El valor es muy inferior para ejecutar la prueba">/home/infinity/Documentos/Selenium_testing_framework_python/src/tests/tst_002.py:22: El valor es muy inferior para ejecutar la prueba</skipped></testcase><testcase classname="tst_002.test_002" name="test_005" time="0.002"><failure message="AssertionError: 'XXXX' not found in 'Bienvenido a la clase de unittest' : No coinciden">self = &lt;src.tests.tst_002.test_002 testMethod=test_005&gt;

    def test_005(self):
        self.Variable_A = "Bienvenido a la clase de unittest"
        self.Variable_B = "XXXX"
    
&gt;       self.assertIn(self.Variable_B, self.Variable_A, f"No coinciden")
E       AssertionError: 'XXXX' not found in 'Bienvenido a la clase de unittest' : No coinciden

tst_002.py:41: AssertionError</failure></testcase><testcase classname="tst_002.test_002" name="test_006" time="0.002"><failure message="AssertionError: unexpectedly identical: 'Bienvenido a la clase de unittest' : No coinciden">self = &lt;src.tests.tst_002.test_002 testMethod=test_006&gt;

    def test_006(self):
        self.Variable_A = "Bienvenido a la clase de unittest"
        self.Variable_B = "Bienvenido a la clase de unittest"
    
&gt;       self.assertIsNot(self.Variable_B, self.Variable_A, f"No coinciden")
E       AssertionError: unexpectedly identical: 'Bienvenido a la clase de unittest' : No coinciden

tst_002.py:47: AssertionError</failure></testcase><testcase classname="tst_003.test_002" name="test_004" time="0.001"><skipped type="pytest.skip" message="El valor es muy inferior para ejecutar la prueba">/home/infinity/Documentos/Selenium_testing_framework_python/src/tests/tst_003.py:20: El valor es muy inferior para ejecutar la prueba</skipped></testcase><testcase classname="tst_003.test_002" name="test_comparacion" time="0.001" /></testsuite></testsuites>